apiVersion: v2
name: mitre-siphon
description: A full text search of the mitre CVE database
type: application
version: 0.2.9
appVersion: "0.2.2"
maintainers:
  - name: bryopsida
    email: 8363252+bryopsida@users.noreply.github.com
dependencies:
  - name: postgresql
    alias: postgresql
    condition: postgresql.enabled
    repository: https://charts.bitnami.com/bitnami
    version: "15.5.32"
  - name: kafka
    alias: kafka
    condition: kafka.enabled
    repository: https://charts.bitnami.com/bitnami
    version: "30.1.2"
